export const FETCHING_STARTED = 'FETCHING_STARTED';
export const ERROR_FETCHING = 'ERROR_FETCHING';
export const TICKERS_FETCHED = 'TICKERS_FETCHED';
export const TICKER_SEARCHED = 'TICKER_SEARCHED';
export const STARTED_SEARCHING = 'STARTED_SEARCHING';
export const ERROR_SEARCHING = 'ERROR_SEARCHING';
